- name: configuring backend
  hosts: backend
  become: yes
  tasks:
  - name: Disable nodejs 
    ansible.builtin.dnf:
        name: nodejs
        state: disabled

  - name: Enable Node.js 20
    ansible.builtin.dnf:
      name: nodejs:20
      state: enabled

  - name: installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present 

      
      