- name: configuring front end server
  hosts: front
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
     name: nginx
     state: present

  - name: enabling and starting nginx
    ansible.builtin.service: 
     name: nginx
     state: started
     enabled: yes

  - name: remove default content in html
    ansible.builtin.file:
     path: /usr/share/nginx/html/
     state: absent

  - name: downloading front end content
    ansible.builtin.get_url:
     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
     path: /tmp/frontend.zip
     

