- name: confirguring my sql server
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: starting mysqld service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes    
