- name: confirguring my sql server
  hosts: mysql
  become: yes
  vars:
    mysql_pass: "ExpenseApp@1"
  tasks:
  - name: installing mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: starting mysqld service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes  

  - name: installing pymysql
    ansible.builtin.pip:
     name: "PyMySQL"   
     state: present

  - name: Collect all info
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_pass }}"
    register: mysql_info  
    ignore_errors: true

  - name: saving above info
    ansible.builtin.debug:
     msg: "{{ mysql_info }}"
          